### PR TITLE
Drop unused stuff

### PR DESCRIPTION
**Pull request by leamas**
LIbraries in shipdriver are not used here so drop them. Same for PLUGIN_USE_SVG, unused after dropping the libs.

### CODE REVIEW

**Comment by leamas** [comment]
I can do local builds OK. The CI builds fails for unrelated reasons, the CI setup needs to be updated.

**Comment by Rasbats** [comment]
Only just starting on UKTides. PLUGIN_USE_SVG is used in icons.cpp etc. Are you saying we need to move to just using SVG?

**Comment by leamas** [comment]
Sorry, and great that you checked me (four eyes sees more than two!). The USE_PLUGIN_SVG is indeed used, I just made something wrong when I checked.

When merging, you have an option to just pick the first commit which drops the libraries. Can you use that?  The plugin builds fine without them, so they are just seemingly just left-overs from when you did the first coipy.

**Comment by leamas** [comment]
> you have an option to just pick the first commit which drops the libraries.

There are actually three commits. You could pick the first two, drop the last

**Comment by Rasbats** [comment]
The ShipDriver template needs to work everywhere, with only edits for the src files and plugin name. Many plugins need those libraries. There is a cost to having them available and not used but is this better than the developer having to think about editing CMakeLists.txt and adding them?

**Comment by leamas** [comment]
>  needs to work everywhere, with only edits for the src files and plugin name. 

I don't see it that way, by my mind is still open. 

The important point for me is that the files under cmake/ should work everywhere. So far I think we agree.

However, each plugin is unique. They use different libraries, different options, different cmake setup and what not. *My* idea, which is different that the frontend thoughts, is that these differences are reflected in CMakeLists. 

CMakeĹists.txt is now around 150 lines, most of which boilerplate code. It should be possible to maintain a unique such file for each plugin. Or? The alternative is a generic jack of all trades, and I simply think this is a much worse alternative.

And, to be honest: carrying libs which are not used is simply bad programming practise.  A program should have as little code, and not least as little dependencies as possible.

OTOH, these are my thoughts... what are yours?

**Comment by Rasbats** [comment]
Is this correct for pushing to OpenCPN/plugins beta? If so it may be worth adding to README-git.md.

    $ git checkout auto
    $ git rebase beta
    $ git checkout beta
    $ git merge --squash auto

And then make a pull request to OpenCPN/plugins beta branch.
Assuming I have tagged the build with ....beta....

**Comment by leamas** [comment]
Basically, yes. However, here are two issues: to create a copy of you artifacts in your own beta repository, so they don't disappear. And, eventually, to make the PR. So the first steps are (assuming you are about to release 1.1.0)

    $ edit CMakeLists, make some minor change in comment or so, just anything...
    $ git commit -am "Preparing 1.1.0-beta1"
    $ git  tag 1.1.0-beta1
    $ git push --tags origin  master

This should create a copy of your tarball in the cloudsmith beta directory.   verify that it is in place. After this make your _git checkout auto, git rebase beta,  git checkout beta, git merge --squash auto_  exactly as you described it

**Comment by leamas** [comment]
We need to document this. Made a PR updating CI.md

**Comment by Rasbats** [comment]
_OTOH, these are my thoughts... what are yours?_

OpenCPN has provided a great sandpit for producing code but I am not a programmer. I feel there are a lot of developers who have ideas for plugins but come from a similar background as myself. 

We should not create barriers that restrict these developers in making their plugins available. Legacy plugins have few restrictions. Managed plugins should be as easy to create as possible. Moving a plugin from legacy to managed should be an easy, well documented process. Perhaps ShipDriver is a good 'reference' plugin, albeit with code that could be improved. For managing other plugins the documentation could highlight the parts of the template that are not used by that plugin. But a starting point is needed.

I started to document the process using my oPlayDo github account but time........

**Comment by leamas** [comment]
>  But a starting point is needed.

Agreed.  And we are getting there, slowly. And, as you point out, some documentation on how to use this is badly needed. Great if you do that...

That said, if there is any build file besides CMakeLIsts.txt which needs to be modified and thus documented we should look careful into it. My basic idea is that CMakeLists.txt should be the only file which should be 'plugin-dependent', so to speak.

**Comment by leamas** [comment]
One of the things that would be great to have is a clean, polished set of patches converting a unmanaged plugin to a managed. This would be some good documentaiton.

But it has to wait until our reference target stabilizes somewhat.

You are aware of the checklist in https://github.com/leamas/OpenCPN/wiki/Plugin-adaptation, right?

**Comment by Rasbats** [comment]
>You are aware of the checklist in https://github.com/leamas/OpenCPN/wiki/Plugin-adaptation, right?

Yes.
Standby for a list of the files that need editing. Quite a long list. Big potential for me to make mistakes, especially those involving the case of plugin name.

**Comment by Rasbats** [comment]
Not so many.

- appveyor.yml
- UKTides-plugin.xml.in
- org.opencpn.OpenCPN.Plugin.UKTides.yaml
- Makefile
- 0001-flatpak-Update-API-lookup-data-dir-using-GetPluginDa.patch

Still making edits to this plugin as a result of the navnux episode

**Comment by leamas** [comment]
Hm, most of that list actually looks sound. But a need to edit a patch :(  Needs some attention, but later...

**Comment by Rasbats** [comment]
Another one:

- ci/circleci-build-flatpak.sh

I was wrong about all the ci/ files not needing edits.

**Comment by Rasbats** [comment]
We seem to have lost the ability to build standalone using the Windows batch file.

 _Building Custom Rule C:/project/opencpn/shipdriver_pi/CMakeLists.txt
  -- Cmake version: 3.18.3.
  -- Building: tarball
  -- Selected upload repository: opencpn/shipdriver-alpha
  -- *** Staging to build ShipDriver_pi ***
  -- Found Gettext: C:/Program Files (x86)/Poedit/GettextTools/bin/msgmerge.exe
   (found version "0.19.8.1")
  -- Found OpenGL: opengl32
  -- Found OpenGL...
  --     Lib: opengl32glu32
  --     Include:
  CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.18/Modules/FindPack
  ageHandleStandardArgs.cmake:165 (message):
  -- Configuring incomplete, errors occurred!
  See also "C:/project/opencpn/shipdriver_pi/build/CMakeFiles/CMakeOutput.log".
    Could NOT find wxWidgets (missing: base core net xml html adv gl)
  Call Stack (most recent call first):
    C:/Program Files (x86)/CMake/share/cmake-3.18/Modules/FindPackageHandleStan
  dardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
    C:/Program Files (x86)/CMake/share/cmake-3.18/Modules/FindwxWidgets.cmake:1
  008 (find_package_handle_standard_args)
    cmake/PluginLibs.cmake:25 (find_package)
    CMakeLists.txt:131 (include)_

**Comment by leamas** [comment]
There are windows problem, I know.. Looking into it now, but shirt of time

**Comment by leamas** [comment]
Anyway, don't spend any time documenting the patch file. It should be removed from that list, full stop.

**Pull request merged**
